name: Deploy Flask App  # Название пайплайна

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода из репозитория
        uses: actions/checkout@v3

      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка Docker-образа
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_app:latest .

      - name: Публикация в Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask_app:latest

  deploy:
    needs: build  # Запускается после успешной сборки
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и развертывание контейнера
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
            docker stop flask_app || true
            docker rm flask_app || true
            docker run -d -p 80:80 --name flask_app ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
