name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Клонируем репозиторий для получения всех исходных файлов

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Логинимся в Docker Hub для пуша Docker образа

      - name: Build Docker image
        run: |
          docker build -t blackcat34/flask_app:1.0.0 .
        # Сборка Docker-образа с тегом

      - name: Push Docker image
        run: |
          docker push blackcat34/flask_app:1.0.0
        # Пушим образ в Docker Hub

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
        # Установка Minikube, если он не установлен

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
        # Установка kubectl для взаимодействия с кластером Kubernetes

      - name: Configure kubectl to use Minikube
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" > minikube.env
          kubectl config set-cluster minikube --server=https://${{ secrets.SERVER_HOST }} --insecure-skip-tls-verify=true
          kubectl config set-context minikube --cluster=minikube
          kubectl config use-context minikube
        # Настройка kubectl для подключения к Minikube

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
        # Применяем манифесты Kubernetes для деплоя приложения

      - name: Wait for deployment to complete
        run: |
          kubectl rollout status deployment flask-app --timeout=300s
        # Ожидаем завершения деплоя приложения

      - name: Restart application
        run: |
          kubectl rollout restart deployment flask-app
        # Перезапускаем приложение после деплоя


