name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl to use Minikube
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" > minikube.env
          echo "Setting Minikube context"
          kubectl config set-cluster minikube --server=https://${{ secrets.SERVER_HOST }} --insecure-skip-tls-verify=true
          kubectl config set-context minikube --cluster=minikube
          kubectl config use-context minikube

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Restart application
        run: |
          kubectl rollout restart deployment flask-app

